services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./server
    ports:
      - "4000:4000"
    env_file: ./server/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/fleetops
      - CLIENT_ORIGIN=http://localhost:5173
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo-data:
